// <auto-generated />
namespace MassCall.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModelChangedd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelChangedd));
        
        string IMigrationMetadata.Id
        {
            get { return "202206201813488_ModelChangedd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
